server:
  port: 8001
spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  zip-kin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率介于0到1之间，1表示全部采集
        probability: 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.spring.entities #所有别名类所在包
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/
      defaultZone: http://www.eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #lease-renewal-interval-in-seconds: 1 Eureka客户端向服务端发送心跳的时间间隔,单位为秒(默认是30秒)
    #lease-expiration-duration-in-seconds: 2 Eureka服务端在收到最后一次心跳后等待时间上限 ,单位为秒(默认是90秒),超时剔除服务