server:
  port: 81
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      #defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/
      defaultZone: http://www.eureka7001.com:7001/eureka/
feign:
  hystrix:
    enabled: true  #在feign中开启hystrix